
networks:
    frontend:
    backend:
       
services:
    webmvc: 
        build:
            context: .\WebMvc
            dockerfile: Dockerfile
        environment:
            - CatalogUrl=http://catalog
            - IdentityUrl=https://${RPGSHOP_EXTERNAL_DNS_NAME_OR_IP}:7101
            - CallBackUrl=https://${RPGSHOP_EXTERNAL_DNS_NAME_OR_IP}:7501/
            - ASPNETCORE_URLS=http://+:80;https://+:443
            - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
            - ASPNETCORE_Kestrel__Certificates__Default__Path=./WebMvc.pfx
        container_name: rpgwebmvc
        ports: 
            - "7500:80"
            - "7501:443"
        networks:
            - frontend
        depends_on:
            - catalog
            - auth
    catalog: 
        build:
            context: .\CatalogApi
            dockerfile: Dockerfile
        image: rpgshop/catalog
        environment:
             - DatabaseServer=mssqlserver
             - DatabaseName=CatalogDb
             - DatabaseUser=sa
             - DatabasePassword=aa123456..
             - ExternalCatalogBaseUrl=http://${RPGSHOP_EXTERNAL_DNS_NAME_OR_IP}:7000
        container_name: rpgcatalogapi
        ports:
             - "7000:80"
        networks:
            - backend
            - frontend
        depends_on:
            - mssqlserver
    auth:
        build: 
            context: .\AuthApi
            dockerfile: Dockerfile
        image: rpgshop/auth
        environment: 
            - MvcClient=https://${RPGSHOP_EXTERNAL_DNS_NAME_OR_IP}:7501
            - DatabaseServer=mssqlserver
            - DatabaseName=AuthDb
            - DatabaseUser=sa
            - DatabasePassword=aa123456..
            - ExternalCatalogBaseUrl=http://${RPGSHOP_EXTERNAL_DNS_NAME_OR_IP}:7000
            - ASPNETCORE_URLS=http://+:80;https://+:443
            - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
            - ASPNETCORE_Kestrel__Certificates__Default__Path=./AuthApi.pfx
        container_name: rpgauthapi
        ports:
            - "7100:80"
            - "7101:443"
        networks:
             - backend
             - frontend
        depends_on:
             - mssqlserver

    mssqlserver:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        ports:
            - "1445:1433"
        container_name: rpgmssqlcontainer
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=aa123456..
        networks:
            - backend